[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "link_reaper_sharktrexer"
version = "0.0.1"
authors = [
  { name="Ibrahim", email="sharktrexer@gmail.com" },
]
description = "Removes dead & copies of links from markdown file and updates redirects."
readme = "README.md"
requires-python = ">=3.9.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]