name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lint
      - uses: astral-sh/ruff-action@v1
        with:
          args: "check"
        
      - name: Format
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
